# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{business_time}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["bokmann"]
  s.date = %q{2011-05-25}
  s.description = %q{Have you ever wanted to do things like "6.business_days.from_now" and have weekends and holidays taken into account?  Now you can.}
  s.email = %q{dbock@codesherpas.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/business_time.rb",
    "lib/business_time/business_days.rb",
    "lib/business_time/business_hours.rb",
    "lib/business_time/config.rb",
    "lib/extensions/date.rb",
    "lib/extensions/fixnum.rb",
    "lib/extensions/time.rb",
    "lib/generators/business_time/config_generator.rb",
    "rails_generators/business_time_config/business_time_config_generator.rb",
    "rails_generators/business_time_config/templates/business_time.rb",
    "rails_generators/business_time_config/templates/business_time.yml",
    "test/helper.rb",
    "test/test_business_days.rb",
    "test/test_business_days_eastern.rb",
    "test/test_business_days_utc.rb",
    "test/test_business_hours.rb",
    "test/test_business_hours_eastern.rb",
    "test/test_business_hours_utc.rb",
    "test/test_calculating_business_duration.rb",
    "test/test_config.rb",
    "test/test_date_extensions.rb",
    "test/test_fixnum_extensions.rb",
    "test/test_time_extensions.rb",
    "test/test_time_with_zone_extensions.rb"
  ]
  s.homepage = %q{http://github.com/bokmann/business_time}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Support for doing time math in business hours and days}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.0.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.0.0"])
  end
end

